# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
       - image: circleci/ruby:2.5.3-node
         environment:
         - PG_HOST=localhost
         - PG_USER=ubuntu

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
       - image: circleci/postgres:10.6
         environment:
         - POSTGRES_USER=ubuntu
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
        
      # Database setup
      - run:
          name: setup
          command: |
            bin/boilerplate/ci/setup
          environment:
            DATABASE_URL: "postgres://ubuntu:@localhost:5432/circle_test"

      # run tests!
      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results
            bin/boilerplate/ci/build
          environment:
            DATABASE_URL: "postgres://ubuntu:@localhost:5432/circle_test"

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
