# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  build:
    docker:
      # https://circleci.com/developer/images/image/cimg/ruby
      - image: cimg/ruby:3.3.6-node
        environment:
        - DATABASE_URL=postgres://ubuntu:@localhost:5432/circle_test

      # https://circleci.com/developer/images/image/cimg/postgres
      - image: cimg/postgres:14.2
        environment:
        - POSTGRES_USER=ubuntu
        - POSTGRES_PASSWORD=totallysecret
    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: "Configure Node version"
          command: |
            grep nodejs .tool-versions | cut -d " " -f 2 > .nvmrc

      - node/install:
          install-yarn: true

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "Gemfile.lock" }}-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v2-dependencies-

      - run:
          name: Install dependencies
          command: |
            gem install bundler
            bundle update --bundler
            bundle install --jobs=4 --retry=3 --path="./vendor/bundle"
            bundle clean --force
            yarn install --check-files

      - save_cache:
          paths:
            - ./vendor/bundle
            - ./node_modules
          key: v2-dependencies-{{ checksum "Gemfile.lock" }}-{{ checksum "yarn.lock" }}

      # Database setup
      - run:
          name: Setup database
          command: |
            bin/boilerplate/ci/setup

      # run tests!
      - run:
          name: Run tests
          command: |
            mkdir /tmp/test-results
            bin/boilerplate/ci/build

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
