# frozen_string_literal: true

require "rails_helper"

RSpec.describe User, :type => :model do
  it { should validate_presence_of(:email) }

  it "can be generated by FactoryBot" do
    expect(FactoryBot.create(:user)).to be_valid
  end
end
