version: 1
update_configs:
  # Keep package.json (& lockfiles) up to date
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"
    version_requirement_updates: "increase_versions_if_necessary"
  # Keep Ruby gems up to date
  - package_manager: "ruby:bundler"
    directory: "/"
    update_schedule: "daily"
    version_requirement_updates: "increase_versions_if_necessary"
